name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3]
        laravel: [10, 11]
        exclude:
          - laravel: 10
            php: 8.3

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer config --no-plugins allow-plugins.php-http/discovery false
          composer require --no-update laravel/framework:^${{ matrix.laravel }}.0
          composer update --prefer-stable --no-interaction

      - name: Pint
        run: vendor/bin/pint --test

      - name: PHPStan
        run: vendor/bin/phpstan analyse --no-progress

      - name: PHPUnit
        run: vendor/bin/phpunit